FROM openjdk:11-jdk

RUN addgroup -g 1000 -S appgroup && \
    adduser -u 1000 -S appuser -G appgroup

USER 1000

VOLUME /tmp
ADD ./build/libs/nolasa.jar app.jar

ENTRYPOINT ["java","-jar","app.jar"]
