version: "3.2"

services:
  app:
    build:
      context: .
    environment:
    - DATASOURCE_URL=${NOLASA_DB_URL}
    - DATASOURCE_USERNAME=${NOLASA_DB_USERNAME}
    - APP_CRON_STRING=0 * * ? * *
    - APP_DRY_RUN_MODE=false
    - LIBRA_ENDPOINTURI=${LIBRA_ENDPOINT_URI}
    - CLOUDWATCH_EXPORT_ENABLED=false
    - CLOUDWATCH_STEP=10m
    ports:
    - 8081:8080
    - 8001:8000