# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appNameEnv: "not-on-libra-auto-search-application"
dryRunMode: "False"
environment: "dev"

nolasa:
  replicaCount: 2 # Two pods to take into accoutn descheduling
  revisionHistoryLimit: 2 # Specifies the number of old ReplicaSets to retain to allow rollback
  minReadySeconds: 10 # Specifies the minimum number of seconds for which a newly created Pod should be ready without any of its containers crashing, for it to be considered available
  strategy:
    type: RollingUpdate # For RollingUpdate, when your deployment is updated, or your pods need to be moved to another node, the cluster will create new instances before terminating the old ones
    rollingUpdate:
      maxSurge: 1 # A complete additional copy of your deployment will be created before any of your old pods are terminated
      maxUnavailable: 0 # Pod must be available at all times

  image:
    repository: "Defined in cp-main-workflow.yml GHA pipeline"
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "65e4ae82695329924d259bbc24e43e299aad7f7c"

  cloudwatch:
    exportEnabled: false
    step: 1h

  dataSource:
    url: "jdbc:oracle:thin:@rds.maat.aws.dev.legalservices.gov.uk:1521:MAATDB"
    username: "MLA"

  cronSchedule: "12 35 * * * *" # Cron schedule for when the matching job gets ran
  libraEndpointUri: "https://laa-infox-dev.apps.live.cloud-platform.service.justice.gov.uk/infoX/gateway"
