# Default values for nolasa-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

appNameEnv: "not-on-libra-auto-search-application"
dryRunMode: "True"
environment: "dev"

# TODO Needs matching with CF templates
nolasa:
  replicaCount: 1
  revisionHistoryLimit: 2
  minReadySeconds: 10
  strategy:
    type: Recreate

  image:
    repository: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/laa-aws-infrastructure/laa-not-on-libra-auto-search-application-dev-ecr
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: "65e4ae82695329924d259bbc24e43e299aad7f7c"

  cloudwatch:
    exportEnabled: false
    step: 1h

  dataSource:
    url: "jdbc:oracle:thin:@rds.maat.aws.dev.legalservices.gov.uk:1521:MAATDB"
    username: "MLA"

  cronSchedule: "0 20 * * * *"
  libraEndpointUri: "http://infox.aws.dev.legalservices.gov.uk/infoX/gateway"
