
package uk.gov.justice._2013._11.magistrates;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LIBRAServicePortType", targetNamespace = "http://www.justice.gov.uk/2013/11/magistrates")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LIBRAServicePortType {


    /**
     * 
     * @param request
     * @return
     *     returns uk.gov.justice._2013._11.magistrates.LibraSearchResponse
     */
    @WebMethod(operationName = "LibraSearch")
    @WebResult(name = "LibraSearchResponse", targetNamespace = "http://www.justice.gov.uk/2013/11/magistrates", partName = "response")
    public LibraSearchResponse libraSearch(
        @WebParam(name = "LibraSearchRequest", targetNamespace = "http://www.justice.gov.uk/2013/11/magistrates", partName = "request")
        LibraSearchRequest request);

}
