
package uk.gov.justice._2013._11.magistrates;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LIBRAServiceService", targetNamespace = "http://www.justice.gov.uk/2013/11/magistrates", wsdlLocation = "file:/Users/mianmahmood/laa-nolasa/src/main/java/LIBRAService.wsdl")
public class LIBRAServiceService
    extends Service
{

    private final static URL LIBRASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException LIBRASERVICESERVICE_EXCEPTION;
    private final static QName LIBRASERVICESERVICE_QNAME = new QName("http://www.justice.gov.uk/2013/11/magistrates", "LIBRAServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/Users/mianmahmood/laa-nolasa/src/main/java/LIBRAService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LIBRASERVICESERVICE_WSDL_LOCATION = url;
        LIBRASERVICESERVICE_EXCEPTION = e;
    }

    public LIBRAServiceService() {
        super(__getWsdlLocation(), LIBRASERVICESERVICE_QNAME);
    }

    public LIBRAServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), LIBRASERVICESERVICE_QNAME, features);
    }

    public LIBRAServiceService(URL wsdlLocation) {
        super(wsdlLocation, LIBRASERVICESERVICE_QNAME);
    }

    public LIBRAServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LIBRASERVICESERVICE_QNAME, features);
    }

    public LIBRAServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LIBRAServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LIBRAServicePortType
     */
    @WebEndpoint(name = "LIBRAService_port")
    public LIBRAServicePortType getLIBRAServicePort() {
        return super.getPort(new QName("http://www.justice.gov.uk/2013/11/magistrates", "LIBRAService_port"), LIBRAServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LIBRAServicePortType
     */
    @WebEndpoint(name = "LIBRAService_port")
    public LIBRAServicePortType getLIBRAServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.justice.gov.uk/2013/11/magistrates", "LIBRAService_port"), LIBRAServicePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LIBRASERVICESERVICE_EXCEPTION!= null) {
            throw LIBRASERVICESERVICE_EXCEPTION;
        }
        return LIBRASERVICESERVICE_WSDL_LOCATION;
    }

}
