apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appNameEnv }}
spec:
  replicas: {{ .Values.nolasa.replicaCount }}
  revisionHistoryLimit: {{ .Values.nolasa.revisionHistoryLimit }}
  minReadySeconds: {{ .Values.nolasa.minReadySeconds }}
  {{- with .Values.nolasa.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .Values.appNameEnv }}
  template:
    metadata:
      labels:
        app: {{ .Values.appNameEnv }}
    spec:
      containers:
      - name: {{ .Values.appNameEnv }}
        image: "{{ .Values.nolasa.image.repository }}:{{ .Values.nolasa.image.tag }}"
        imagePullPolicy: {{ .Values.nolasa.image.pullPolicy }}
        env:
          - name: APP_DRY_RUN_MODE
            value: "{{ .Values.dryRunMode }}"
          - name: CLOUDWATCH_EXPORT_ENABLED
            value: "{{ .Values.nolasa.cloudwatch.exportEnabled }}"
          - name: CLOUDWATCH_STEP
            value: {{ .Values.nolasa.cloudwatch.step }}
          - name: DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: "nolasa-env-variables"
                key: DATASOURCE_URL
          - name: DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: "nolasa-env-variables"
                key: DATASOURCE_USERNAME
          - name: DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "nolasa-env-variables"
                key: DATASOURCE_PASSWORD
          - name: INFOX_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: "nolasa-infox-client-secret"
                key: INFOX_CLIENT_SECRET
          - name: APP_CRON_STRING
            value: {{ .Values.nolasa.cronSchedule }}
          - name: LIBRA_ENDPOINTURI
            value: {{ .Values.nolasa.libraEndpointUri }}
