name: Deploy to Kubernetes in Cloud Platform

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      github-sha:
        required: true
        type: string
      parameter-file:
        required: true
        type: string
    secrets:
      kube-cluster:
        required: true
      kube-namespace:
        required: true
      kube-cert:
        required: true
      kube-token:
        required: true
      
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:  
      - uses: actions/checkout@v3    
      - run: |
          echo "${{ secrets.kube-cert }}" > ca.crt
          kubectl config set-cluster ${{ secrets.kube-cluster }} --certificate-authority=./ca.crt --server=https://${{ secrets.kube-cluster }}
          kubectl config set-credentials cd-serviceaccount --token=${{ secrets.kube-token }}
          kubectl config set-context ${{ secrets.kube-cluster }} --cluster=${{ secrets.kube-cluster }} --user=cd-serviceaccount --namespace=${{ secrets.kube-namespace }}
          kubectl config use-context ${{ secrets.kube-cluster }}
      - run: |
          cd helm_deploy/not-on-libra-auto-search-application
          helm upgrade not-on-libra-auto-search-application -f ${{ inputs.parameter-file }} . --namespace ${{ secrets.kube-namespace }} --install --set nolasa.image.tag=${{ inputs.github-sha }}